from typing import TypedDict, List, Optional, Annotated
import operator

class Source(TypedDict):
    url: str
    title: str
    content: str
    relevance_score: float

class AgentState(TypedDict):
    topic: str
    search_queries: List[str]           # queries generated by search agent
    raw_search_results: List[dict]      # raw Tavily results
    scraped_sources: Annotated[List[Source], operator.add]  # accumulated, not overwritten
    critic_feedback: Optional[str]      # "Not enough sources on pricing" etc.
    critic_passed: Optional[bool]                 # True = move to writing, False = retry search, None initially
    report_sections: List[dict]         # structured sections from writer
    final_report: Optional[str]         # markdown report string
    citations: Optional[List[dict]]               # [{index: 1, url: ..., title: ...}]
    current_step: str                   # tracks which agent ran last
    step_count: int                     # prevents infinite loops (cap at 5)
    progress_messages: Annotated[List[str], operator.add]  # streamed to frontend
    error: Optional[str]